### ISSUE TITLE
Jobs never stops showing it is running

### ISSUE THREAD

**Issue by SSSikora** [jamesmh/coravelpro#48] opened 2022-07-12 17:58 UTC
First off, wonderful product! Thank you.

I am testing an upgrade from Coravel to Coravel Pro and when I click run on a job in the UI it runs but then continues to show it is running in the "Recent" section. I can click on run again and it does but it just keeps leaving additional entries in the "Recent" showing it running with the indicator spinning on all of them. Any thoughts?

Much appreciated,
Scott

**Comment by jamesmh** [comment] 2022-07-12 18:46
Thanks!

So, if you run a job, wait a few seconds (assuming your job doesn't actually need more time to execute) and then refresh the page - does the entry at the bottom EVER show completed?

This is expected since any job you execute is not run immediately but placed in a queue that runs every so often (every 30 sec by default I think - that's configurable). So if your task usually takes 10 seconds to run, it may in fact be "running" for 40-ish seconds since you're waiting while the queue is consumed too.

Otherwise, open your browser's developer console when trying this an see if any errors come up.

IF you find nothing, try using [the global error handler](https://docs.coravel.net/Scheduler/#global-error-handling) and dump the exception to your console - or just re-throw the exception to gain visibility on what's happening.

Let me know if you do or don't find anything👍

**Comment by SSSikora** [comment] 2022-07-12 19:58
Appreciate the quick response, James.

They never complete my test jobs show they have been running for hours. Here is my test class:

public class SitePhotoServiceTest : IInvocable
{
    private readonly ILogger<SitePhotoServiceTest> logger;

    public SitePhotoServiceTest(ILogger<SitePhotoServiceTest> logger)
    {
        this.logger = logger;
    }

    public Task Invoke()
    {
        logger.LogInformation("Site Photos Service Test via Coravel Pro");
        return Task.CompletedTask;
    }
}

I will see what else I can find but am not sure how use the global error handling for something that only exists in the UI and was registered as a service via DI. Also, the console window of the browser shows nothing wrong. I will keep checking to see what I can find.

Thanks,
Scott

**Comment by jamesmh** [comment] 2022-07-13 00:41
What does your `configureService()` etc. look like?

Also, which version of Coravel and Coravel.Pro are you using?

Thanks!

**Comment by SSSikora** [comment] 2022-07-13 01:23
James,

Coravel Pro 4.0.2 is the only package reference. Are there reasons to also include the base non-pro version? Maybe I've missed something regarding that.

We have an ASP.NET Core 6 application. MVC and Blazor server hybrid. The program.cs lines are as follows:

builder.Services.AddCoravelPro(typeof(PortalDbContext));

and

app.UseCoravelPro();

As a side note, I made payment for Pro a little earlier today, well worth the nominal fee as this is really helping our project.

Appreciate the help,
Scott

**Comment by jamesmh** [comment] 2022-07-13 01:42
Hmmm did you make sure to run the database migrations? (probably did...just to make sure lol).

Otherwise. try to make sure each of those calls are the very end of each `ConfigureServices()` and `Configure()` methods.

Finally, try to explicitly reference the most up-to-date version of the base Coravel nuget package... it's possible you've found an issue with the dependencies🤷‍♂️ lol.

Glad you're finding the tools useful! If you don't mind, briefly: what are the most helpful pieces you're finding with Coravel Pro?

**Comment by SSSikora** [comment] 2022-07-13 12:36
Hello James. Yes, migrations have been committed.

Maybe the issue lies in what the screenshot below is showing? The last two jobs were run just before the refresh time and show a, UTC time I guess, so maybe there is something there.

Unfortunately, I ran across another even more breaking issue for me. I use Telerik ASP.NET Core controls and they require that Newtonsoft be set as follows to work:

.AddNewtonsoftJson(options => options.SerializerSettings.ContractResolver = new Newtonsoft.Json.Serialization.DefaultContractResolver());

Sadly, that breaks Coravel when it makes its calls for data. Any ideas on this?

And to answer your question about usage. I picked up Coravel primarily because we started adding a bunch of background jobs to the app and I need a way to manage them without having to write my own UI. After locating your Nugget I then started leveraging the mail as well.


![CoravelIssue](https://user-images.githubusercontent.com/7399496/178733663-259b8462-151a-468a-b155-74830642a0bd.png)

**Comment by jamesmh** [comment] 2022-07-15 20:11
The json issue is something that's not addressed yet, but it's come up before. Bummer lol. It's possible that the other issues are caused by this (unless you were having issues before you made that change?)

It's something I'll have to look into to see if I can explicitly set the serializer for coravel pro's endpoints, but leave the default for everything else.

**Comment by jamesmh** [comment] 2022-07-16 03:57
I released new release candidate nuget package. You'll have to manually set the specific package since it's not an official release yet (wait to get feedback on this + a few new features to bake in).

Try to install `Coravel.Pro.5.0.0-rc-1` manually. This should fix the JSON issues. Let me know if the jobs are still hanging or not 👍

**Comment by SSSikora** [comment] 2022-07-18 13:31
Thank you, James.

Added this package and it did indeed correct the json issue so that Coravel can now coexist with my existing site. It did not however, correct the issue I am seeing with the task showing it is still running. This sample job in the photo logs a message, and it is doing just that, and I can run the job again a couple of minutes later without issue so it appears as though there is just an issue with the UI. I am still seeing that time difference between the last refresh and start/end.

![CoravelIssue2](https://user-images.githubusercontent.com/7399496/179522473-8b158c0b-85d0-4de9-9d40-7c0f1ac970a1.png)


Appreciate all the help on this, it is a great addition to our application.

**Comment by SSSikora** [comment] 2022-08-03 11:26
James,

Wondering if you had any additional thoughts on why this page is still not working quite right?

![CoravelIssue3](https://user-images.githubusercontent.com/7399496/182596621-657d5c95-4cf5-43be-84a5-45df654bdaae.png)

The scheduling and firing of jobs are working perfectly, however.

Thanks for  the help - Scott

**Comment by jamesmh** [comment] 2022-08-05 21:42
@SSSikora so, if you run one job, and it hangs and says "running" indefinitely... what happens to that job on the UI if you stop/restart the application? Does it still say "running" (it shouldn't...)

**Comment by SSSikora** [comment] 2022-08-08 11:36
James - Stopping and starting the application doesn't change anything. As soon as it restarts it shows running even though the jobs has completed which I can see from the logging I am doing.

**Comment by SSSikora** [comment] 2022-09-13 10:44
James,

Just an FYI, moved up to the latest release and am still showing jobs as running forever. And just because it's been a while, they do run and successfully complete, both as instance jobs and scheduled ones, it is just the UI that seems not to acknowledge this for some reason.

-Scott

**Comment by jamesmh** [comment] 2022-09-13 11:39
Thanks for letting me know. Normally, there's an event handler in background for Coravel Pro that is triggered after a job is competed. For some reason, that event handler (I suspect?) is not firing.

I'd be open to doing a video chat to have a quick look at your code to see if anything pops out?

Another option is to debug your application just at the end of your job until you come to [this method in the base Coravel library.](https://github.com/jamesmh/coravel/blob/2996465ccf069ee4c113f4781a05b88b514ab63a/Src/Coravel/Events/Dispatcher.cs#L55). That method should (a) trigger and (b) find an event handler and trigger it. That handler is supposed to update the job's associate item in the database and assign an "endDate" to it (which isn't happening, so the UI sees a `null` endDate).

Let me know what you think 👍

**Comment by SSSikora** [comment] 2023-06-07 19:46
Hello James,

We finally got around to taking a look at this and the reason we are having trouble is because of EF Core and tracking. Please see the attached picture of my communications with one of our developers and see what you think.

Thanks - Scott
![CoravelIssue](https://github.com/jamesmh/coravelpro/assets/7399496/16e82a9d-9ad8-4906-82f7-e3f4b7e4bf29)

**Comment by jamesmh** [comment] 2023-06-08 18:27
Thanks Scott. This makes sense (finally!). I'll look to fix/test this and post updates for you 👍

**Comment by SSSikora** [comment] 2023-06-09 11:12
Sounds good, thank you James.

**Comment by jamesmh** [comment] 2023-06-20 01:32
This is fixed in Coravel 5.1.2. Will close. Thanks for the help @SSSikora!

**Closed as completed by jamesmh** 2023-06-20 01:32 UTC
