### ISSUE TITLE
Threading error

### ISSUE THREAD

**Issue by mark-simpkins** [jamesmh/coravelpro#40] opened 2020-12-15 11:47 UTC
Hi,

I'm setting up CoravelPro to test how it works.

The web UI runs up fine but after clicking around a few times I get "A second operation started on this context before a previous operation completed." See the full error below.

Any suggestions on how to resolve this?

Kind Regards,

Mark

Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint '/Scheduling'
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.10\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.InvalidOperationException: A second operation started on this context before a previous operation completed. This is usually caused by different threads using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Coravel.Pro.Features.Jobs.UseCases.ScheduledJobHistoryQuery.GetHistory(Int32 page)
   at Coravel.Pro.Coravel.Pages.SchedulingModel.OnPostGetHistory(GetHistoryModel model)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by jamesmh** [comment] 2020-12-15 12:54
Hey Mark, 

Are you using .NET Core 3.1 with the latest version of Coravel Pro? What version of EF Core?

I've yet to see that error so my first thought is something particular with that version of EF...but you never know!

Thanks :)

**Comment by mark-simpkins** [comment] 2020-12-15 14:11
Hi James,

- .net core 3.1
- Coravel.Pro 4.0.1
- EF Core 3.1.10

The database is MySql 8.0.21 with Pomelo.EntityFrameworkCore.MySql 3.2.4

Another factor which might be relevant is the context is registered via Autofac (7.1.0) in these Startup.cs:

```
services.AddCoravelPro(typeof(CoravelContext));

var builder = new ContainerBuilder();

builder.RegisterType<CoravelContext>().InstancePerLifetimeScope();

builder.Populate(services);

ApplicationContainer = builder.Build();
```

Kind Regards,

Mark

**Comment by mark-simpkins** [comment] 2020-12-15 14:12
Sorry, I also meant to mention, whenever I've seen that error before it's been caused by a missing await (if that helps!).

Mark

**Comment by jamesmh** [comment] 2020-12-15 14:42
Hmmm autofac is the issue. Internally CoravelPro only supports the built in .NET Core DI injection and makes assumptions about it.

Right now Coravel Pro only supports the built-in DI system :(

**Comment by mark-simpkins** [comment] 2020-12-15 16:06
I've dropped Autofac from the solution. I still get the error but I've narrowed it down to when I click 'run' on a job it can take 10 seconds before it fires it. If I then click on 'Scheduling' before it's run I get the threading exception.

The task is just:

```
    public class TestJob2 : IInvocable
    {
        public TestJob2()
        {
        }

        public async Task Invoke()
        {
            Trace.WriteLine("TestJob2");
        }
    }
```

**Comment by jamesmh** [comment] 2020-12-15 16:20
K so I have an idea from looking at the source code. I suspect the issue happens specifically with the Mysql provider. I've not seen this issue with the other providers that I've tested and that clients have used (typically SQL server and Postgres).

But there is a potential issue I can see - but will have to test, etc. to find out.

**Comment by mark-simpkins** [comment] 2020-12-15 19:18
No problem, it's not urgent as it's not in production yet.

If you do figure it out let me know and I'll give it another test.

**Comment by jamesmh** [comment] 2020-12-15 20:17
Will do 👍

**Comment by kirby14** [comment] 2021-03-24 20:55
I'm getting a similar issue when running scheduled jobs. My list of completed scheduled jobs shows up empty most (but not all) of the time as well, even through the data is in the DB.

2021-03-24 13:27:47.101 -05:00 [ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: A second operation was started on this context before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Coravel.Pro.Features.Jobs.UseCases.ScheduledJobHistoryQuery.GetHistory(Int32 page)
   at Coravel.Pro.Coravel.Pages.SchedulingModel.OnPostGetHistory(GetHistoryModel model)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task

I started the project in .Net 5 which I don't think is officially supported yet, so I assume step 1 is to drop back down to 3.1?

**Comment by jamesmh** [comment] 2021-03-25 11:15
@kirby14  are you also using MySQL?

**Comment by kirby14** [comment] 2021-03-25 13:07
@jamesmh Sorry, no I am using MS SQL 2014 but the same thing happens using the SQL Express in VS while debugging.

**Comment by 5nyper** [comment] 2021-04-26 07:20
I am also experiencing this error, using 
dotnet 3.1, EF core 3.1.0 and Coravel Pro 4.0.2

**Comment by jamesmh** [comment] 2021-04-26 12:02
Thanks @5ynatra for letting me know. I'm hoping to get around to working on Coravel Pro again. Had some personal hurdles for the last few months... I think the last year-ish has been quite a frustrating series of events for many people lol

Will keep this thread updated as I move on to working on this. 👍

**Comment by jamesmh** [comment] 2021-05-18 03:53
Update: I'm working on figuring out the issues here. So far I've confirmed/replicated two separate issues:

1. An exception causing issues on the `/Scheduling` page (the first comment on the thread by @mark-simpkins, which was also mentioned by @kirby14 that he was experiencing the same issue)
2. An exception happens when (also mentioned by @mark-simpkins) running a job (which actually _queues_ a job to be run) and then quickly, while that job is still queued, try to schedule it.

 @mark-simpkins suggestion that a missing `await` somewhere might be causing issues is "half" correct lol. I have some code that was intentionally executing two `async` queries and then combining the data later. With tools like Dapper, for example (since it's my "go-to" DB tooling), it supports doing this pretty easy. EF Core... not so much since it's all so magical (the issue ultimately is that EF core context uses one and only one DB connection, whereas with something like Dapper you can easily create a new connection for each query). I was under the impression that this was fine as long as you weren't mutating/saving any data to the `DbContext`. Even with `AsNoTracking` this is not supported, since it's the underlying DB connection that cannot issue concurrent queries. Nothing new for those who understand these nitty-gritty details of EF core 😆 .

So that answers issue no. 1. Thanks for helping to point that out @mark-simpkins. Should have this fixed in the next few days.

Still looking at why issue no. 2 is happening, since these are two separate HTTP requests and therefore two separate DI scopes and DB contexts altogether... but will have to do a bit more digging for that one. The exception I'm getting is a weird one that at face value doesn't make sense. So more digging to be had.

Thanks for waiting. I know it's been long wait. I had lost some tools that I need to do this work and recently have re-acquired these (covid didn't help...) I'm hoping to improve things and be more responsive from now on 😄 .

**Comment by jamesmh** [comment] 2021-05-18 03:59
Just to add another anecdotal note on top of my last comment: I've read that EF Core 2.1 > 3.0 had some breaking changes for some concurrency related internals. This might explain why these issues have only come up for EF Core 3.0/3.1 and up, but never for 2.1/2.2 and lower.

Fortunately (maybe) most places I manually had to create a DI scope, grab a new `DbContext` from that scope, and dispose - as opposed to just getting it injected in the constructor of a controller, etc. Just a note for anyone else who needs to do this...

The docs explain this way around the issue here -> https://docs.microsoft.com/en-us/ef/core/dbcontext-configuration/#implicitly-sharing-dbcontext-instances-via-dependency-injection

**Comment by jamesmh** [comment] 2021-05-21 12:25
@mark-simpkins @kirby14 version 4.0.2 has the fix. Give it a whirl and let me know if there are any issues etc. I'll close this thread for now 👍

**Closed as completed by jamesmh** 2021-05-21 12:25 UTC
