### ISSUE TITLE
UseCoravelPro() error

### ISSUE THREAD

**Issue by XardasLord** [jamesmh/coravelpro#8] opened 2019-07-20 16:29 UTC
I have an error at this line: `app.UseCoravelPro()`. The error says:

> System.InvalidOperationException: 'No service for type 'GP.SS.Database.SaldeoSynchronizatorContext' has been registered.'

But according to the documentation I have registered it:

```
services.AddDbContext<ISaldeoSynchronizatorContext, SaldeoSynchronizatorContext>( opts => opts.UseOracle(Configuration.GetConnectionString("SaldeoSynchronizatorDB"), b => b.MigrationsAssembly(typeof(ISaldeoSynchronizatorContext).Namespace)) );

services.AddCoravelPro(typeof(SaldeoSynchronizatorContext));
```

**Comment by jamesmh** [comment] 2019-07-20 17:46
Try `services.AddCoravelPro(typeof(ISaldeoSynchronizatorContext));` - although I'm not totally sure if that would work.

**Comment by jamesmh** [comment] 2019-07-20 17:47
The issue is that whatever type you pass to `AddCoravelPro` has to be registered as the actual type in the service container vs. a resolved type. Let me know 👍

**Comment by XardasLord** [comment] 2019-07-20 17:51
@jamesmh Thanks for your very fast answer :)

I tried it `services.AddCoravelPro(typeof(ISaldeoSynchronizatorContext))` earlier and got this message: 

> System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
> Could not load file or assembly 'System.DirectoryServices.Protocols, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 

But I also tried to register DbContext like following (without interface):
```
services.AddDbContext<SaldeoSynchronizatorContext>(
                opts => opts.UseOracle(Configuration.GetConnectionString("SaldeoSynchronizatorDB"),
                    b => b.MigrationsAssembly(typeof(SaldeoSynchronizatorContext).Namespace))
            );
```
But then I got this error message:

> System.InvalidOperationException: 'Unable to resolve service for type 'GP.SS.Database.ISaldeoSynchronizatorContext' while attempting to activate 'GP.SS.Business.SynchronizationService'.'

**Comment by jamesmh** [comment] 2019-07-20 17:55
Did you try this combination?

```c#
services.AddDbContext<SaldeoSynchronizatorContext>(
                opts => opts.UseOracle(Configuration.GetConnectionString("SaldeoSynchronizatorDB"),
                    b => b.MigrationsAssembly(typeof(SaldeoSynchronizatorContext).Namespace))
            );

services.AddCoravelPro(typeof(SaldeoSynchronizatorContext));
```

**Comment by XardasLord** [comment] 2019-07-20 17:56
Yes, then I got this error:

> System.InvalidOperationException: 'Unable to resolve service for type 'GP.SS.Database.ISaldeoSynchronizatorContext' while attempting to activate 'GP.SS.Business.SynchronizationService'.'

EDIT: @jamesmh Wait, but this error is because I inject the dbcontext interface in another service... Hmm but isn't your library prepared for the injectable dbcontext?

**Comment by XardasLord** [comment] 2019-07-20 18:24
@jamesmh 
I removed interface for DbContext and replaced it just to inject the dbContext class in other services.
Now I have this error:

> System.Reflection.ReflectionTypeLoadException: 'Unable to load one or more of the requested types.
> Could not load file or assembly 'System.DirectoryServices.Protocols, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by XardasLord** [comment] 2019-07-20 18:29
I solved the problem by adding nuget package **System.DirectoryServices.Protocols**. There is nothing in a documentation about it - maybe you can add some info about it? :)

**Comment by jamesmh** [comment] 2019-07-20 22:39
That doesn't sound like an issue with Coravel Pro, but looks like some other transient dependencies that was missing.

What version of .NET Core are you using?

**Comment by XardasLord** [comment] 2019-07-21 08:18
I'm using .NET Core 2.2

**Comment by jamesmh** [comment] 2019-07-21 16:20
K. Coravel Pro has no dependency on DirectoryServices. Sounds like the either the Oracle provider or potentially something else in perhaps another project (maybe?) has a transitive dependency on that package - for some reason.

I'll close this this now 👍 Glad you figure it out 😊

**Closed as completed by jamesmh** 2019-07-21 16:20 UTC
